### ISSUE TITLE
Issue in React!

### ISSUE THREAD

**Issue by crackstatus** [anderspitman/redpill#4]
Followed your guide but still not able to display the matrix rain and in the backend the github api seems to be working. Cannot able to render the view and can you update your examples with React sample project.

**Comment by anderspitman** [comment]
Hey @crackstatus, unfortunately I don't really have extra time to invest in this. It was really just a weekend hack to make a cool background for my personal website. I'm happy to answer any specific questions you have if I can but won't be able to make a React wrapper.
